# Generated by Django 5.2.6 on 2025-10-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(help_text='Que sucedio en la fecha?', max_length=200)),
                ('descripcion_m', models.TextField(help_text='Descripcion del evento')),
                ('descripcion_d', models.TextField(help_text='Descripcion del evento')),
            ],
        ),
    ]
