# Generated by Django 5.2.6 on 2025-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fechas',
            index=models.Index(fields=['fecha'], name='fechas_fech_fecha_cdaeda_idx'),
        ),
    ]
