# Generated by Django 5.2.6 on 2025-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0002_fechas_fechas_fech_fecha_cdaeda_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechas',
            options={'ordering': ['-fecha'], 'verbose_name': 'Fecha Importante', 'verbose_name_plural': 'Fechas Importantes'},
        ),
        migrations.AlterField(
            model_name='fechas',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='fechas',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha__isnull', False)), fields=('fecha',), name='fecha_no _repetida'),
        ),
    ]
