# Generated by Django 5.2.6 on 2025-10-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(help_text='Título de la imagen', max_length=200),
        ),
        migrations.AddIndex(
            model_name='galeria',
            index=models.Index(fields=['-fecha'], name='galeria_gal_fecha_5e7c32_idx'),
        ),
    ]
