# Generated by Django 5.2.6 on 2025-10-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_galeria_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Galería'},
        ),
    ]
